apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80          # Exposed in the cluster
      targetPort: 80    # Port your app runs on in the container
  type: ClusterIP       # Internal access (use LoadBalancer for external)
